version: '3'

services:

  proxy:
    build: ./config/nginx
    image: gps-nginx
    ports:
      - '81:3000'
      - '82:80'
    depends_on:
      - postgres
      - webhost
    networks:
      - gps-network
    restart: unless-stopped

  react:
    build: ./config/react
    image: gps-react
    volumes:
      - ./src/frontend:/usr/app
    depends_on:
      - webhost
    networks:
      - gps-network
    restart: unless-stopped

  webhost:
    build: ./config/php
    image: gps-php
    volumes:
      - ./log/apache2:/var/log/apache2
      - ./src/backend:/var/www/html
    depends_on:
      - postgres
    networks:
      - gps-network
    restart: unless-stopped

  postgres:
    build: ./config/postgres
    image: gps-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./log/postgresql:/var/log/postgresql
    ports:
      - '5432:5432'  # This is just for pgAdmin access
    networks:
      gps-network:
        aliases:
          - dns-postgres
    restart: unless-stopped

volumes:
  pgdata:

networks:
  gps-network:
