version: '3'

services:

  proxy:
    build: ./config/nginx
    image: custom-nginx
    ports:
      - '80:80'
    depends_on:
      - postgres
      - webhost
    networks:
      - lamp-network
    restart: unless-stopped

  webhost:
    build: ./config/php
    image: custom-php
    volumes:
      - ./log/apache2:/var/log/apache2
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - lamp-network
    restart: unless-stopped

  postgres:
    build: ./config/postgres
    image: custom-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./log/postgresql:/var/log/postgresql
    ports:
      - '5432:5432'  # This is just for pgAdmin access
    networks:
      lamp-network:
        aliases:
          - dns-postgres
    restart: unless-stopped

volumes:
  pgdata:

networks:
  lamp-network:
